# SPDX-FileCopyrightText: 2024-present Richard Dahl <richard@dahl.us>
#
# SPDX-License-Identifier: MIT
site_name: un0
theme:
   name: material
plugins:
   - search
   - mkdocstrings
nav:
   - Home: index.md
   - About: about.md
   - License: license.md
   - FAQ: faq.md
   - Getting Started: getting_started.md
   - Structure: structure.md
   - Commands: commands.md
   - DB: 
      - DB Tools: db/tool.md
      - DB Tool SQL: db/tool_sql.md
      - Table Tools: db/table_tools.md
      - Un0Obj: db/models.md
   - Authorization:
      - Enums: auth/enums.md
      - Models: auth/models.md
      - Tables: auth/tables.md
